-- ============================================================================
-- MIGRACION 001 - FACTURAS ESPECIALES Y TRIBUTOS (RF-06, RF-14, RF-15, RF-16)
-- Esquema: PROYECTOANALISIS | Responsable: CXP_DOCUMENTO / DETALLE / TRIBUTO
-- ============================================================================
-- Se ejecuta SOBRE una instalacion CXP existente (17 tablas, 102 FK).
-- Es re-ejecutable: cada paso comprueba si ya fue aplicado y no borra datos.
--
-- 1. CK_CXP_DOC_TIPO: agrega FACTURA_ESPECIAL conservando los 14 tipos actuales.
--    Primero se crea y valida la restriccion nueva y solo despues se retira la
--    anterior, de modo que la tabla nunca queda sin la restriccion.
-- 2. CXP_REGLA_TRIBUTARIA: reglas de IVA/ISR parametrizables, versionadas y con
--    vigencia. Una modificacion crea una version nueva; la anterior se conserva.
-- 3. CXP_DOCUMENTO_TRIBUTO.ID_REGLA_TRIBUTARIA: identifica la regla (version)
--    aplicada. Porcentaje, base y monto ya se guardan en la fila del tributo,
--    por lo que los cambios futuros de reglas no alteran documentos procesados.
-- 4. CXP_FACTURA_ESPECIAL: extension 1:1 de CXP_DOCUMENTO con los datos fiscales
--    del proveedor, la revision, la emision y la constancia numerada.
-- 5. Parametros: serie, correlativos sin huecos y aprobadores autorizados.
--
-- No crea triggers. Las reglas del flujo (revision, aprobacion, emision unica,
-- anulacion) se aplican en la capa de servicios dentro de transacciones.
-- Reversion: 001_facturas_especiales_tributos_rollback.sql
-- ============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

PROMPT 1. Ampliando CK_CXP_DOC_TIPO con FACTURA_ESPECIAL...
DECLARE
    V_CONDICION VARCHAR2(4000);
    V_N NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_N FROM USER_TABLES WHERE TABLE_NAME = 'CXP_DOCUMENTO';
    IF V_N = 0 THEN
        RAISE_APPLICATION_ERROR(-20301, 'No existe CXP_DOCUMENTO. Instalar primero el DDL de CXP.');
    END IF;

    SELECT MAX(SEARCH_CONDITION_VC) INTO V_CONDICION
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = 'CXP_DOCUMENTO' AND CONSTRAINT_NAME = 'CK_CXP_DOC_TIPO';

    IF V_CONDICION IS NOT NULL AND INSTR(V_CONDICION, 'FACTURA_ESPECIAL') > 0 THEN
        DBMS_OUTPUT.PUT_LINE('CK_CXP_DOC_TIPO ya admite FACTURA_ESPECIAL. Sin cambios.');
    ELSE
        -- Restriccion nueva con los tipos actuales + FACTURA_ESPECIAL (ENABLE VALIDATE).
        EXECUTE IMMEDIATE q'[
            ALTER TABLE CXP_DOCUMENTO ADD CONSTRAINT CK_CXP_DOC_TIPO_V2 CHECK
            (TIPO_DOCUMENTO IN ('FACTURA', 'FACTURA_CAMBIARIA', 'NOTA_CREDITO',
                                'NOTA_DEBITO', 'RECIBO', 'REEMBOLSO',
                                'LIQUIDACION_VIATICO', 'GASTO_CAJA_CHICA',
                                'CUOTA_CONTRATO', 'CUOTA_PRESTAMO',
                                'OBLIGACION_FISCAL', 'SALDO_INICIAL',
                                'COMPROBANTE_SERVICIO', 'OTRO',
                                'FACTURA_ESPECIAL')) ENABLE VALIDATE]';
        IF V_CONDICION IS NOT NULL THEN
            EXECUTE IMMEDIATE 'ALTER TABLE CXP_DOCUMENTO DROP CONSTRAINT CK_CXP_DOC_TIPO';
        END IF;
        EXECUTE IMMEDIATE 'ALTER TABLE CXP_DOCUMENTO RENAME CONSTRAINT CK_CXP_DOC_TIPO_V2 TO CK_CXP_DOC_TIPO';
        DBMS_OUTPUT.PUT_LINE('CK_CXP_DOC_TIPO actualizado.');
    END IF;
END;
/

PROMPT 2. Creando CXP_REGLA_TRIBUTARIA...
DECLARE
    V_N NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_N FROM USER_TABLES WHERE TABLE_NAME = 'CXP_REGLA_TRIBUTARIA';
    IF V_N > 0 THEN
        DBMS_OUTPUT.PUT_LINE('CXP_REGLA_TRIBUTARIA ya existe. Sin cambios.');
        RETURN;
    END IF;
    EXECUTE IMMEDIATE q'[
        CREATE TABLE CXP_REGLA_TRIBUTARIA (
            ID_REGLA_TRIBUTARIA NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            CODIGO_REGLA        VARCHAR2(30)   NOT NULL,
            VERSION_REGLA       NUMBER(6)      DEFAULT 1 NOT NULL,
            ID_REGLA_ANTERIOR   NUMBER,
            TIPO_DOCUMENTO      VARCHAR2(30)   DEFAULT 'FACTURA_ESPECIAL' NOT NULL,
            TIPO_TRIBUTO        VARCHAR2(15)   NOT NULL,
            CODIGO_TRIBUTO      VARCHAR2(30)   NOT NULL,
            NOMBRE_TRIBUTO      VARCHAR2(120)  NOT NULL,
            PORCENTAJE          NUMBER(9,6)    DEFAULT 0 NOT NULL,
            MONTO_FIJO          NUMBER(18,2)   DEFAULT 0 NOT NULL,
            BASE_DESDE          NUMBER(18,2)   DEFAULT 0 NOT NULL,
            BASE_HASTA          NUMBER(18,2),
            SOBRE_EXCEDENTE     CHAR(1)        DEFAULT 'N' NOT NULL,
            MONEDA              VARCHAR2(3),
            VIGENTE_DESDE       DATE           NOT NULL,
            VIGENTE_HASTA       DATE,
            ESTADO              VARCHAR2(20)   DEFAULT 'VIGENTE' NOT NULL,
            MOTIVO_CAMBIO       VARCHAR2(500),
            CREADA_POR          NUMBER         NOT NULL,
            FECHA_CREACION      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
            MODIFICADA_POR      NUMBER,
            FECHA_MODIFICACION  TIMESTAMP,
            CONSTRAINT PK_CXP_REGLA_TRIB PRIMARY KEY (ID_REGLA_TRIBUTARIA),
            CONSTRAINT UK_CXP_RTRIB_VERSION UNIQUE (CODIGO_REGLA, VERSION_REGLA),
            CONSTRAINT FK_CXP_RTRIB_ANT FOREIGN KEY (ID_REGLA_ANTERIOR)
                REFERENCES CXP_REGLA_TRIBUTARIA (ID_REGLA_TRIBUTARIA),
            CONSTRAINT FK_CXP_RTRIB_CREA FOREIGN KEY (CREADA_POR)
                REFERENCES USUARIO (USU_ID_USUARIO),
            CONSTRAINT FK_CXP_RTRIB_MOD FOREIGN KEY (MODIFICADA_POR)
                REFERENCES USUARIO (USU_ID_USUARIO),
            CONSTRAINT CK_CXP_RTRIB_TIPO CHECK (TIPO_TRIBUTO IN ('IMPUESTO', 'RETENCION')),
            CONSTRAINT CK_CXP_RTRIB_MONTOS CHECK
                (PORCENTAJE >= 0 AND PORCENTAJE <= 100 AND MONTO_FIJO >= 0 AND BASE_DESDE >= 0
                 AND (BASE_HASTA IS NULL OR BASE_HASTA >= BASE_DESDE)),
            CONSTRAINT CK_CXP_RTRIB_EXCED CHECK (SOBRE_EXCEDENTE IN ('S', 'N')),
            CONSTRAINT CK_CXP_RTRIB_MONEDA CHECK (MONEDA IS NULL OR LENGTH(MONEDA) = 3),
            CONSTRAINT CK_CXP_RTRIB_VIGENCIA CHECK (VIGENTE_HASTA IS NULL OR VIGENTE_HASTA >= VIGENTE_DESDE),
            CONSTRAINT CK_CXP_RTRIB_ESTADO CHECK (ESTADO IN ('VIGENTE', 'REEMPLAZADA', 'FINALIZADA')),
            CONSTRAINT CK_CXP_RTRIB_VERSION CHECK (VERSION_REGLA > 0),
            CONSTRAINT CK_CXP_RTRIB_CAMBIO CHECK (VERSION_REGLA = 1 OR MOTIVO_CAMBIO IS NOT NULL)
        )]';
    EXECUTE IMMEDIATE q'[
        CREATE INDEX IX_CXP_RTRIB_APLICA ON CXP_REGLA_TRIBUTARIA
            (TIPO_DOCUMENTO, TIPO_TRIBUTO, CODIGO_TRIBUTO, VIGENTE_DESDE, VIGENTE_HASTA)]';
    DBMS_OUTPUT.PUT_LINE('CXP_REGLA_TRIBUTARIA creada.');
END;
/

PROMPT 3. Vinculando CXP_DOCUMENTO_TRIBUTO con la regla aplicada...
DECLARE
    V_N NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_N FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'CXP_DOCUMENTO_TRIBUTO' AND COLUMN_NAME = 'ID_REGLA_TRIBUTARIA';
    IF V_N = 0 THEN
        -- Columna opcional: los tributos existentes (sin regla) no se modifican.
        EXECUTE IMMEDIATE 'ALTER TABLE CXP_DOCUMENTO_TRIBUTO ADD (ID_REGLA_TRIBUTARIA NUMBER)';
        EXECUTE IMMEDIATE q'[
            ALTER TABLE CXP_DOCUMENTO_TRIBUTO ADD CONSTRAINT FK_CXP_TRIB_REGLA
            FOREIGN KEY (ID_REGLA_TRIBUTARIA) REFERENCES CXP_REGLA_TRIBUTARIA (ID_REGLA_TRIBUTARIA)]';
        EXECUTE IMMEDIATE 'CREATE INDEX IX_CXP_TRIB_REGLA ON CXP_DOCUMENTO_TRIBUTO (ID_REGLA_TRIBUTARIA)';
        DBMS_OUTPUT.PUT_LINE('ID_REGLA_TRIBUTARIA agregada.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ID_REGLA_TRIBUTARIA ya existe. Sin cambios.');
    END IF;
END;
/

PROMPT 4. Creando CXP_FACTURA_ESPECIAL...
DECLARE
    V_N NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_N FROM USER_TABLES WHERE TABLE_NAME = 'CXP_FACTURA_ESPECIAL';
    IF V_N > 0 THEN
        DBMS_OUTPUT.PUT_LINE('CXP_FACTURA_ESPECIAL ya existe. Sin cambios.');
        RETURN;
    END IF;
    EXECUTE IMMEDIATE q'[
        CREATE TABLE CXP_FACTURA_ESPECIAL (
            ID_FACTURA_ESPECIAL   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            ID_DOCUMENTO          NUMBER         NOT NULL,
            PROVEEDOR_NOMBRE      VARCHAR2(200)  NOT NULL,
            PROVEEDOR_NIT         VARCHAR2(20),
            PROVEEDOR_CUI         VARCHAR2(20),
            PROVEEDOR_DIRECCION   VARCHAR2(300),
            DESCRIPCION_OPERACION VARCHAR2(1000) NOT NULL,
            REVISADO_POR          NUMBER,
            FECHA_REVISION        TIMESTAMP,
            OBSERVACION_REVISION  VARCHAR2(1000),
            ESTADO_EMISION        VARCHAR2(20)   DEFAULT 'PENDIENTE' NOT NULL,
            NUMERO_CONSTANCIA     VARCHAR2(40),
            FECHA_EMISION         TIMESTAMP,
            EMITIDO_POR           NUMBER,
            HASH_CONSTANCIA       VARCHAR2(64),
            CREADO_POR            NUMBER         NOT NULL,
            FECHA_CREACION        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
            CONSTRAINT PK_CXP_FACTURA_ESP PRIMARY KEY (ID_FACTURA_ESPECIAL),
            CONSTRAINT UK_CXP_FESP_DOC UNIQUE (ID_DOCUMENTO),
            CONSTRAINT UK_CXP_FESP_CONST UNIQUE (NUMERO_CONSTANCIA),
            CONSTRAINT FK_CXP_FESP_DOC FOREIGN KEY (ID_DOCUMENTO)
                REFERENCES CXP_DOCUMENTO (ID_DOCUMENTO),
            CONSTRAINT FK_CXP_FESP_REV FOREIGN KEY (REVISADO_POR)
                REFERENCES USUARIO (USU_ID_USUARIO),
            CONSTRAINT FK_CXP_FESP_EMI FOREIGN KEY (EMITIDO_POR)
                REFERENCES USUARIO (USU_ID_USUARIO),
            CONSTRAINT FK_CXP_FESP_CREA FOREIGN KEY (CREADO_POR)
                REFERENCES USUARIO (USU_ID_USUARIO),
            CONSTRAINT CK_CXP_FESP_ID_FISCAL CHECK (PROVEEDOR_NIT IS NOT NULL OR PROVEEDOR_CUI IS NOT NULL),
            CONSTRAINT CK_CXP_FESP_ESTADO CHECK (ESTADO_EMISION IN ('PENDIENTE', 'EMITIDA', 'ANULADA')),
            -- Una constancia emitida siempre tiene numero, fecha, emisor y codigo de respaldo.
            CONSTRAINT CK_CXP_FESP_EMISION CHECK (
                (ESTADO_EMISION = 'PENDIENTE' AND NUMERO_CONSTANCIA IS NULL AND FECHA_EMISION IS NULL)
                OR (ESTADO_EMISION = 'EMITIDA' AND NUMERO_CONSTANCIA IS NOT NULL AND FECHA_EMISION IS NOT NULL
                    AND EMITIDO_POR IS NOT NULL AND HASH_CONSTANCIA IS NOT NULL)
                OR ESTADO_EMISION = 'ANULADA'
            ),
            CONSTRAINT CK_CXP_FESP_HASH CHECK (HASH_CONSTANCIA IS NULL OR LENGTH(HASH_CONSTANCIA) = 64)
        )]';
    DBMS_OUTPUT.PUT_LINE('CXP_FACTURA_ESPECIAL creada.');
END;
/

PROMPT 5. Cargando parametros de facturas especiales...
-- Serie y correlativos: el correlativo se bloquea con FOR UPDATE al asignar un
-- numero, por lo que no hay duplicados ni huecos. La serie es editable.
MERGE INTO CXP_PARAMETRO P
USING (
    SELECT 'CXP_FACTURA_ESPECIAL' GRUPO_PARAMETRO, 'SERIE' CODIGO,
           'Serie de facturas especiales' NOMBRE, 'FESP' VALOR_TEXTO,
           CAST(NULL AS NUMBER) VALOR_NUMERO FROM DUAL
    UNION ALL
    SELECT 'CXP_FACTURA_ESPECIAL', 'CORRELATIVO_FACTURA',
           'Ultimo numero de factura especial asignado', NULL, 0 FROM DUAL
    UNION ALL
    SELECT 'CXP_FACTURA_ESPECIAL', 'CORRELATIVO_CONSTANCIA',
           'Ultimo numero de constancia emitido', NULL, 0 FROM DUAL
) S
ON (P.GRUPO_PARAMETRO = S.GRUPO_PARAMETRO AND P.CODIGO = S.CODIGO)
WHEN NOT MATCHED THEN
    INSERT (GRUPO_PARAMETRO, CODIGO, NOMBRE, VALOR_TEXTO, VALOR_NUMERO, ACTIVO)
    VALUES (S.GRUPO_PARAMETRO, S.CODIGO, S.NOMBRE, S.VALOR_TEXTO, S.VALOR_NUMERO, 'S');

-- Aprobadores autorizados: se registran desde Configuracion > Parametros con
--   GRUPO_PARAMETRO = 'CXP_FE_APROBADOR', CODIGO = 'USUARIO_<id>',
--   VALOR_NUMERO = USU_ID_USUARIO, VALOR_TEXTO = ROL_ID_ROL con el que aprueba, ACTIVO = 'S'.
-- No se precargan usuarios: deben existir en la tabla comun USUARIO.

COMMIT;

PROMPT Migracion 001 aplicada.
