-- ============================================================================
-- SOLO PARA PRUEBAS LOCALES - TABLAS COMUNES MINIMAS
-- ============================================================================
-- Crea versiones minimas de las tablas de otros modulos (USUARIO, PROVEEDOR,
-- ROL, DEPARTAMENTO, CXC_*, CMP_*) con las claves y columnas que el DDL de CXP
-- valida. NO usar en la base compartida del equipo: alli existen las reales.
-- Se detiene si alguna ya existe para no tocar datos reales.
-- ============================================================================
SET SERVEROUTPUT ON SIZE UNLIMITED
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
    V_N NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_N FROM USER_TABLES
     WHERE TABLE_NAME IN ('USUARIO', 'PROVEEDOR', 'ROL', 'DEPARTAMENTO', 'CXC_SUCURSALES', 'CXC_EMPRESAS',
                          'CXC_CONDICIONES_CREDITO', 'CXC_FORMAS_PAGO', 'CXC_DOCUMENTOS', 'CMP_FACTURA_CXP',
                          'CMP_ORDEN_COMPRA', 'CMP_RECEPCION_BODEGA', 'CMP_ARTICULO',
                          'CMP_DETALLE_ORDEN_COMPRA', 'CMP_DETALLE_RECEPCION');
    IF V_N > 0 THEN
        RAISE_APPLICATION_ERROR(-20401, 'Ya existen tablas comunes; este script es solo para una base de pruebas vacia.');
    END IF;
END;
/

CREATE TABLE USUARIO (USU_ID_USUARIO NUMBER CONSTRAINT PK_USUARIO PRIMARY KEY, USU_NOMBRE VARCHAR2(150) NOT NULL, USU_USUARIO VARCHAR2(50));
CREATE TABLE ROL (ROL_ID_ROL NUMBER CONSTRAINT PK_ROL PRIMARY KEY, ROL_NOMBRE VARCHAR2(100) NOT NULL);
CREATE TABLE PROVEEDOR (PRO_ID_PROVEEDOR NUMBER CONSTRAINT PK_PROVEEDOR PRIMARY KEY, PRO_NOMBRE_ENTIDAD VARCHAR2(200) NOT NULL, PRO_NIT VARCHAR2(20));
CREATE TABLE DEPARTAMENTO (DEP_ID_DEPARTAMENTO NUMBER CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY, DEP_NOMBRE VARCHAR2(100));
CREATE TABLE CXC_EMPRESAS (ID_EMPRESA NUMBER CONSTRAINT PK_CXC_EMPRESAS PRIMARY KEY, NOMBRE VARCHAR2(150));
CREATE TABLE CXC_SUCURSALES (ID_SUCURSAL NUMBER CONSTRAINT PK_CXC_SUCURSALES PRIMARY KEY, NOMBRE VARCHAR2(150));
CREATE TABLE CXC_CONDICIONES_CREDITO (ID_CONDICION NUMBER CONSTRAINT PK_CXC_COND PRIMARY KEY, NOMBRE VARCHAR2(150));
CREATE TABLE CXC_FORMAS_PAGO (ID_FORMA_PAGO NUMBER CONSTRAINT PK_CXC_FORMAS PRIMARY KEY, NOMBRE VARCHAR2(150));
CREATE TABLE CXC_DOCUMENTOS (ID_DOCUMENTO NUMBER CONSTRAINT PK_CXC_DOCUMENTOS PRIMARY KEY, NUMERO_DOCUMENTO VARCHAR2(80), SERIE VARCHAR2(40));
CREATE TABLE CMP_FACTURA_CXP (FAC_NO_FACTURA VARCHAR2(50) CONSTRAINT PK_CMP_FACTURA PRIMARY KEY, FAC_FECHA_FACTURA DATE, FAC_TOTAL_FACTURA NUMBER);
CREATE TABLE CMP_ORDEN_COMPRA (OCO_NO_PO VARCHAR2(20) CONSTRAINT PK_CMP_OC PRIMARY KEY, OCO_FECHA_EMISION DATE);
CREATE TABLE CMP_RECEPCION_BODEGA (RBO_NO_RECEPCION VARCHAR2(20) CONSTRAINT PK_CMP_REC PRIMARY KEY, RBO_FECHA_RECEPCION DATE);
CREATE TABLE CMP_ARTICULO (ART_CODIGO_ARTICULO VARCHAR2(20) CONSTRAINT PK_CMP_ART PRIMARY KEY, ART_NOMBRE VARCHAR2(150));
CREATE TABLE CMP_DETALLE_ORDEN_COMPRA (DOC_ID_DETALLE_PO NUMBER CONSTRAINT PK_CMP_DOC PRIMARY KEY, DOC_DESCRIPCION VARCHAR2(200));
CREATE TABLE CMP_DETALLE_RECEPCION (DRE_ID_DETALLE_RECEPCION NUMBER CONSTRAINT PK_CMP_DRE PRIMARY KEY, DRE_DESCRIPCION VARCHAR2(200));

-- Datos de prueba: usuarios (1 registra, 2 aprobador autorizado, 3 sin autorizacion),
-- un rol aprobador, dos proveedores sin capacidad de facturar y una sucursal.
INSERT INTO USUARIO VALUES (1, 'Analista CXP (prueba)', 'analista');
INSERT INTO USUARIO VALUES (2, 'Contador aprobador (prueba)', 'contador');
INSERT INTO USUARIO VALUES (3, 'Auxiliar sin autorizacion (prueba)', 'auxiliar');
INSERT INTO ROL VALUES (1, 'Aprobador de facturas especiales');
INSERT INTO PROVEEDOR VALUES (1, 'Juan Perez (agricultor, prueba)', '1234567-8');
INSERT INTO PROVEEDOR VALUES (2, 'Maria Lopez (artesana, prueba)', NULL);
INSERT INTO DEPARTAMENTO VALUES (1, 'Compras');
INSERT INTO CXC_EMPRESAS VALUES (1, 'Universidad (prueba)');
INSERT INTO CXC_SUCURSALES VALUES (1, 'Sede central');
INSERT INTO CXC_FORMAS_PAGO VALUES (1, 'Transferencia');
COMMIT;
