import oracledb from 'oracledb';
import { getConnection } from '../../../../config/database';
import type { Pago, CreatePagoInput, UpdatePagoInput } from '@erp/contracts';
interface Row { ID_PAGO:number; ID_CLIENTE:number; ID_FORMA_PAGO:number; ID_MONEDA:number; ID_BANCO:number|null; FECHA_PAGO:Date; MONTO:number; NUMERO_REFERENCIA:string|null; ESTADO:string; }
const mapRow=(r:Row):Pago=>({idPago:r.ID_PAGO,idCliente:r.ID_CLIENTE,idFormaPago:r.ID_FORMA_PAGO,idMoneda:r.ID_MONEDA,idBanco:r.ID_BANCO,fechaPago:r.FECHA_PAGO?.toISOString()??'',monto:r.MONTO,numeroReferencia:r.NUMERO_REFERENCIA,estado:r.ESTADO});
export async function findAll({page,limit,search}:{page:number;limit:number;search?:string}){const c=await getConnection();try{const offset=(page-1)*limit;const where=search?`WHERE UPPER(p.NUMERO_REFERENCIA) LIKE UPPER(:search) OR UPPER(p.ESTADO) LIKE UPPER(:search) OR TO_CHAR(p.ID_PAGO) LIKE :search`:'';const sb=search?{search:`%${search}%`}:{ };const data=await c.execute<Row>(`SELECT p.ID_PAGO,p.ID_CLIENTE,p.ID_FORMA_PAGO,p.ID_MONEDA,p.ID_BANCO,p.FECHA_PAGO,p.MONTO,p.NUMERO_REFERENCIA,p.ESTADO FROM CXC_PAGOS p ${where} ORDER BY p.FECHA_PAGO DESC,p.ID_PAGO DESC OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY`,{...sb,offset,limit});const cnt=await c.execute<{TOTAL:number}>(`SELECT COUNT(*) TOTAL FROM CXC_PAGOS p ${where}`,sb);return{data:(data.rows??[]).map(mapRow),total:cnt.rows?.[0]?.TOTAL??0};}finally{await c.close();}}
export async function findById(id:number){const c=await getConnection();try{const r=await c.execute<Row>(`SELECT ID_PAGO,ID_CLIENTE,ID_FORMA_PAGO,ID_MONEDA,ID_BANCO,FECHA_PAGO,MONTO,NUMERO_REFERENCIA,ESTADO FROM CXC_PAGOS WHERE ID_PAGO=:id`,{id});return r.rows?.[0]?mapRow(r.rows[0]):null;}finally{await c.close();}}
export async function create(i:CreatePagoInput){const c=await getConnection();try{const r=await c.execute<{id:number[]}>(`INSERT INTO CXC_PAGOS (ID_CLIENTE,ID_FORMA_PAGO,ID_MONEDA,ID_BANCO,FECHA_PAGO,MONTO,NUMERO_REFERENCIA,ESTADO) VALUES (:idCliente,:idFormaPago,:idMoneda,:idBanco,TO_DATE(:fechaPago,'YYYY-MM-DD'),:monto,:numeroReferencia,:estado) RETURNING ID_PAGO INTO :id`,{idCliente:i.idCliente,idFormaPago:i.idFormaPago,idMoneda:i.idMoneda,idBanco:i.idBanco??null,fechaPago:i.fechaPago,monto:i.monto,numeroReferencia:i.numeroReferencia??null,estado:i.estado,id:{dir:oracledb.BIND_OUT,type:oracledb.NUMBER}});await c.commit();return r.outBinds!.id[0];}catch(e){await c.rollback();throw e;}finally{await c.close();}}
export async function update(id:number,i:UpdatePagoInput){const f:string[]=[];const b:any={id};if(i.idCliente!==undefined){f.push('ID_CLIENTE=:idCliente');b.idCliente=i.idCliente;}if(i.idFormaPago!==undefined){f.push('ID_FORMA_PAGO=:idFormaPago');b.idFormaPago=i.idFormaPago;}if(i.idMoneda!==undefined){f.push('ID_MONEDA=:idMoneda');b.idMoneda=i.idMoneda;}if(i.idBanco!==undefined){f.push('ID_BANCO=:idBanco');b.idBanco=i.idBanco;}if(i.fechaPago!==undefined){f.push(`FECHA_PAGO=TO_DATE(:fechaPago,'YYYY-MM-DD')`);b.fechaPago=i.fechaPago;}if(i.monto!==undefined){f.push('MONTO=:monto');b.monto=i.monto;}if(i.numeroReferencia!==undefined){f.push('NUMERO_REFERENCIA=:numeroReferencia');b.numeroReferencia=i.numeroReferencia;}if(i.estado!==undefined){f.push('ESTADO=:estado');b.estado=i.estado;}if(!f.length)return;const c=await getConnection();try{await c.execute(`UPDATE CXC_PAGOS SET ${f.join(',')} WHERE ID_PAGO=:id`,b);await c.commit();}catch(e){await c.rollback();throw e;}finally{await c.close();}}
export async function remove(id:number){const c=await getConnection();try{await c.execute(`DELETE FROM CXC_PAGOS WHERE ID_PAGO=:id`,{id});await c.commit();}catch(e){await c.rollback();throw e;}finally{await c.close();}}

export async function listOptions(){const c=await getConnection();try{const r=await c.execute<{ID_PAGO:number;MONTO:number;FECHA_PAGO:Date}>(`SELECT ID_PAGO,MONTO,FECHA_PAGO FROM CXC_PAGOS ORDER BY FECHA_PAGO DESC,ID_PAGO DESC FETCH FIRST 100 ROWS ONLY`);return(r.rows??[]).map(x=>({id:x.ID_PAGO,label:`Pago #${x.ID_PAGO} - ${x.MONTO}`}));}finally{await c.close();}}
